### PR TITLE
Add a github phpunit action

### LINKED ISSUE #7: Automate tests
### Description

Use github actions to automate the tests

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by n3f**
Fixes #7 

#### Changes proposed in this Pull Request

* Adds a github workflow for running phpunit actions

#### Testing instructions

* Verify that the PHPUnit test runs below and succeeds

### CODE REVIEW

**Review by millerf — CHANGES_REQUESTED** [review]
I understand this is adding tests for everything.
Could you also output the coverage somewhere? Either in the README [with a badge](https://github.com/marketplace/actions/code-coverage-summary#badge) or just in the tests themselves

**Comment by n3f** [comment]
Isn't this good enough? (The PHPUnit one is mine and you can see it on this PR if you show all the checks).  

image

I will look at adding a badge to README too...

**Comment by millerf** [comment]
@n3f It doesn't run [coverage](https://docs.phpunit.de/en/10.5/code-coverage.html), does it?

Screenshot 2024-10-23 at 17 14 40

**Comment by n3f** [comment]
I updated phpunit to report code coverage easily, but the problem is putting the generated image url somewhere.  (e.g. you can add to a PR comment, but storing it generically for each branch requires a 3rd party service to track the status like codecov).

There is a [convoluted method](https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa) to store the result in a gist and then update the PR template to have the developer update a badge with the PR number... (This would work to store an overall badge too).

I'm going to implement just adding as a comment to the PR for now.

**Comment by millerf** [comment]
> I'm going to implement just adding as a comment to the PR for now.

Yes, that is fine. If the coverage can be seen anywhere (for example in the PR tests, it is fine...)

**Comment by millerf** [comment]
That's pretty cool @n3f !

**Review by millerf — APPROVED** [review]
LGTM!

**Pull request merged**
